name: Call Download APK Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-download-apk:
    runs-on: ubuntu-latest
    env:
     APP_NAME: 'fidelity-investments'
    steps:    
    -  uses: Yakov5776/gh-apkmirror-dl@main
       with:
        org: ${{ env.APP_NAME }}
        repo: ${{ env.APP_NAME }}
        version: '3.96'
        bundle: false
        
        
    
    -   uses: actions/upload-artifact@v4
        with:
           name: APK
           path: .
